### ISSUE TITLE
Can't seem to run any examples provided?

### ISSUE THREAD

**Issue by kehrazy** [zesterer/chumsky#433]
When studying the documentation provided, I've noticed that you have some examples in the `examples/` folder.

When I setup my project with
```
cargo new --bin chumsky_example ./chumsky_example && cd chumsky_example && cargo add chumsky
```
and put any example code in the `src/main.rs` I get a lot of unresolved imports, e.g. `extra::Err` or `ValueInput` errors. There is no `input` mod in the library, as far as cargo is concerned.

Thank you for your work, hope this gets resolved.

**Comment by kehrazy** [comment]
> See my answer on #432 - the current examples are for the still in alpha `1.0` version, and will not work with the `0.9` version cargo installs. The `0.9` version tag should contain working examples.

Ah, I see. I would probably annotate the `examples/` with "this wont work with 0.9".

Thank you!
